volumes:
  prometheus_data_vol:
  grafana_data_vol:
  jaeger_data_vol:

networks:
  observability_network:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data_vol:/prometheus
    networks:
      - observability_network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
      - '3000:3000'
    volumes:
      - grafana_data_vol:/var/lib/grafana
    networks:
      - observability_network

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
      - ./collector-output-trace.json:/etc/otelcol-contrib/collector-output-trace.json
      - ./collector-output-meter.json:/etc/otelcol-contrib/collector-output-meter.json
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - observability_network
    depends_on:
      - prometheus
      - jaeger
  
  jaeger:
    image: jaegertracing/all-in-one:1.55
    volumes:
      - jaeger_data_vol:/jaeger_data
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - observability_network
